import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Welcome from '../components/Welcome'

const Home: NextPage = () => {
  return (
    <div>
      <Head key="head">
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <Welcome />
        <About />
      </main>
    </div>
  )
}

export default Home
